### ISSUE TITLE
An error occurred while converting from Yolo format to coco format.

### ISSUE THREAD

**Issue by amzpun** [laclouis5/globox#21]
#yolotococo format

from globox import AnnotationSet

yolo = AnnotationSet.from_yolo_darknet(
    folder= r'C:\Users\Desktop\nem-process\label' ,
    image_folder= r'C:\Users\Desktop\nem-process\images'
)

yolo.show_stats()
cocodata=yolo.save_coco(r'C:\Users\Downloads\globox-main\globox-main')

The output of show_stats() is 
      Database Stats      
┏━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃ Label ┃ Images ┃ Boxes ┃
┡━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0     │     41 │   269 │
│ 1     │      6 │     8 │
├───────┼────────┼───────┤
│ Total │     46 │   277 │
└───────┴────────┴───────┘

Error displayed as:

  File "C:\Users\anaconda3\envs\tf\lib\site-packages\globox\annotationset.py", line 602, in to_coco
    raise ValueError("For COCO, mappings from labels and image ids to integer ids are required. They can be provided either by argument or automatically by the `AnnotationSet` instance if it was created with `AnnotationSet.from_coco()` or `AnnotationSet.from_coco_results()`. You can also set `auto_ids` to True to automatically create image and label ids (warning: this could cause unexpected compatibility issues with other COCO datasets).")

**Comment by laclouis5** [comment]
Read the error message, it tells you how to solve the issue.
