### ISSUE TITLE
NameError: name 'AnnotationSet' is not defined

### ISSUE THREAD

**Issue by bryceburrows** [laclouis5/globox#22]
So i did a pip install globox

then in my python...

"
import globox

yolo_preds = AnnotationSet.from_yolo(
    folder="D:\AI\mydata\labels",
    image_folder="D:\AI\mydata\images")
"

following the demo code...
I then get 
Exception has occurred: NameError
name 'AnnotationSet' is not defined

what have i missed?

**Comment by h4pZ** [comment]
I just had this issue. `AnnotationSet` is defined inside globox. So you can do either

```python
import globox

yolo_preds = globox.AnnotationSet.from_yolo(
folder="D:\AI\mydata\labels",
image_folder="D:\AI\mydata\images")
```

or

```python
from globox import AnnotationSet

yolo_preds = AnnotationSet.from_yolo(
folder="D:\AI\mydata\labels",
image_folder="D:\AI\mydata\images")
```

or import all if you will :) `from globox import *`

**Comment by laclouis5** [comment]
This is how Python import statements work and not a Globox issue. @h4pZ summed up the different ways you can import `AnnotationSet`. Another solution not mentioned is to import Globox and use a short name like it is usually done with Numpy: 

```python
import globox as gx

yolo_preds = gx.AnnotationSet.from_yolo(
  folder="D:\AI\mydata\labels",
  image_folder="D:\AI\mydata\images"
)
```
