### ISSUE TITLE
Unable to solve the missed image problem

### ISSUE THREAD

**Issue by rentainhe** [laclouis5/globox#23]
I use coco128 as an example, and coco128 has some labels that did not match to any images, and which will raise the bug:
```python
from globox import AnnotationSet

yolo = AnnotationSet.from_yolo(
    folder="./coco128/coco128/labels/train2017",
    image_folder="./coco128/coco128/images/train2017"
)


>>>
AssertionError: File ./coco128/coco128/images/train2017/000000000659.jpg does not exists, unable to read the image size.
```

Do you have any idea to solve it ? I'm not sure if it's a bug or we need to add some new features for this situation

**Comment by laclouis5** [comment]
Can you check if the image `000000000659.jpg` exists in the `./coco128/coco128/images/train2017/` folder? If this is not the case, you should add it before running this function since each annotation file must have a corresponding image for the YOLO format.

**Comment by rentainhe** [comment]
> 

Thanks for your reply, I will try to remove the missed label and image and try this API again
