### ISSUE TITLE
Single Image score

### ISSUE THREAD

**Issue by pathikg** [laclouis5/globox#29]
In my scenario, I need to compute the `mAP.5:.95` metric for an individual image output. 
I have two files at my disposal, e.g. `ground_truth.txt` and `prediction.txt`.  I am seeking guidance on how to utilize the `globox` library to calculate the scores for a single file.

**Comment by laclouis5** [comment]
A one-file dataset is still a dataset. You can use the regular `AnnotationSet` methods to read the annotations, for instance `AnnotationSet.from_yolo_v7` and others.
