### ISSUE TITLE
Missing area in COCO's .json output?

### ISSUE THREAD

**Issue by reydelsol** [laclouis5/globox#30]
https://github.com/laclouis5/globox/blob/005789310c25d6bd2bee2edf409b34680fdab38b/src/globox/annotationset.py#L754

Is there a field missing for "area"?

Annotations might have:

“annotations”: {
    “id”: int,
    “image_id: int”,
    “category_id”: int
    “segmentation”: RLE or [polygon],
    “area”: float,
    “bbox”: [x,y,width,height],
    “iscrowd”: 0 or 1
}

**Comment by reydelsol** [comment]
Thank you for the explanation. I was using another tool to analyze the .json file saved with globox. It attempts to access the area field for a bounding box and throws an error as a result.

**Comment by laclouis5** [comment]
Thanks for the clarification. What is the other tool you used? I could add the `area` field if this simplifies this workflow.

**Comment by reydelsol** [comment]
I used datatsetinsights from Unity's Perception. This function threw the error:
https://github.com/Unity-Technologies/datasetinsights/blob/0705bead5e592bdfe59e10a749ed7bf5264a2b68/datasetinsights/stats/object_detection_stats.py#L26

**Comment by laclouis5** [comment]
I updated the package so that `area` and `segmentation` fields are populated for COCO export. Could you try updating Globox to its last version (v2.1.2) then try exporting the annotations to COCO again and finally import in Perception SDK?
