### ISSUE TITLE
globox summary: error: the following arguments are required: input

### ISSUE THREAD

**Issue by seabass1217** [laclouis5/globox#32]
I'm want to use globox as a command-line tool on a Windows 10 system within Anaconda.  The repo installed fine, but I cannot access a Yolo dataset.  I have attempted to use both Windows and Unix file path styles.   

Below is an image of the error.  

All the images and .txt files are in the LACEx folder.  Any help is greatly appreciated.

Thanks,

![image](https://github.com/laclouis5/globox/assets/86954802/2803b598-455d-4e55-b276-f65500b0feb9)

**Comment by laclouis5** [comment]
It looks like your forgot to specify the `input` folder which is the folder where YOLO annotations are stored. Usually this folder is the same as the image folder since the images are stores alongside the corresponding annotations.

**Comment by seabass1217** [comment]
Thank you for your response. Below is the input path that I'm using. The input path is 'G:\Transparent&Sythetic\SyntheticDataSets\LACEx' 

globox summary --format yolo-darknet --img_folder G:\Transparent&Sythetic\SyntheticDataSets\LACEx

**Comment by laclouis5** [comment]
Ok, so its the same path as the image folder, could you try:

```
globox summary --format yolo-darknet --img_folder G:\Transparent&Sythetic\SyntheticDataSets\LACEx G:\Transparent&Sythetic\SyntheticDataSets\LACEx
```

**Comment by seabass1217** [comment]
I tried your recommended path and still no success.  Let me try to install your repo on Linux and see if that resolves the problem.

Thank you for your help!

**Comment by laclouis5** [comment]
Ok, let me know if this works then. Could you share the error you get when you tried the last command I suggested please?

**Comment by seabass1217** [comment]
Here is the error from your suggested command:

![image](https://github.com/laclouis5/globox/assets/86954802/e6155ac3-5cd4-45ec-b1f8-970b122e4070)

**Comment by seabass1217** [comment]
I installed the repo on Ubuntu and I receive the below error:

![image](https://github.com/laclouis5/globox/assets/86954802/86286690-fd82-4db1-94c6-f943508e607a)

**Comment by laclouis5** [comment]
Both errors suggest that the directories do not exist and this likely means that the paths you passed to Globox are wrong.

On Windows, you can copy the path to a file or folder with a right-click and then "Copy as Path".

On On Ubuntu, it looks like your folder is `/80mm`, i.e. a folder at the root of your filesystem and not relative to the folder from where you issue the command, which may not be what you want.
