### ISSUE TITLE
Relax globox numpy version requirements so it can coexist with tensorflow

### ISSUE THREAD

**Issue by fabito** [laclouis5/globox#35]
**Is your feature request related to a problem? Please describe.**
globox numpy version requirements conflicts with latest tensorflow 2.12.0

```
# tensorflow 
numpy<1.24,>=1.22 (from tensorflow==2.12.0)

# globox 
numpy<2.0.0,>=1.24.3 (from globox==2.1.3)

globox 2.1.3 requires numpy<2.0.0,>=1.24.3, but you have numpy 1.23.1 which is incompatible.
```

**Describe the solution you'd like**
Relax numpy version requirements, if possible, so I can add both dependencies to my project.

**Comment by laclouis5** [comment]
Thanks for the contribution, I'll release a new version with this fix soon.
