### ISSUE TITLE
Yolo txt To coco json Conversion 

### ISSUE THREAD

**Issue by Addoxx** [laclouis5/globox#37]
Hello Louis. 

I am trying to convert segmentation annotations from yolov8 txt format into coco json format so as to be able to use with Labelme tool.   I tried to use the following code: 

```python
from globox import AnnotationSet

predictions = AnnotationSet.from_yolo_v5("/Block/labels", image_folder="/Block/images")

predictions.save_coco("coco_preds.json", label_to_id={"person": 0, "bicycle": 1, "car": 2, "motorcycle": 3, "airplane": 4}, imageid_to_id={im: i for i, im in enumerate(sorted(predictions.image_ids))})
```

I get the following error: 

```
AssertionError: File /Block/images/Block_338.jpg does not exists, unable to read the image size.
```

All my images are in PNG format, is that the source of the error, or am I doing something wrong? 

Environment:
 - Ubuntu 20.04
 - Globox version 2.2.0

Looking forward to your reply.

Thanks in advance,
Adhok

**Comment by Addoxx** [comment]
No it didnt help. I tried multiple formats like yolo_v5, yolo_v7, yolo-darknet and even passed img_ext argument as .png but didnt help. I am stuck with the following error:

globox.errors.FileParsingError: Error while reading file 'Block/labels/Block_338.txt': Syntax error in txt annotation file.

**Comment by laclouis5** [comment]
This means that the annotations files are malformed and do not follow te YOLO format specifications. 

Can you share the content of this annotation file please?

**Comment by Addoxx** [comment]
Louis, 

Below is the snippet of the annotation file in txt format that is generated by YOLO auto-annotation generator as given here [https://docs.ultralytics.com/models/sam/?h=auto+anno#sam-prediction-example](url):

2 0.8698225021362305 0.44078946113586426 0.8694526553153992 0.441447377204895 0.8690828680992126 0.441447377204895 0.8687130212783813 0.4421052634716034 0.8687130212783813 0.4447368383407593 0.86834317445755 0.44539472460746765 0.86834317445755 0.45460525155067444 0.8679733872413635 0.4552631676197052 0.8679733872413635 0.4559210538864136 0.86834317445755 0.45657894015312195 0.86834317445755 0.47171053290367126 0.8687130212783813 0.47236841917037964 0.8687130212783813 0.47828948497772217 0.8690828680992126 0.47894737124443054 0.8690828680992126 0.48552632331848145 0.8694526553153992 0.4861842095851898 0.8694526553153992 0.49671053886413574 0.8698225021362305 0.4973684251308441 0.8698225021362305 0.5092105269432068 0.870192289352417 0.5098684430122375 0.870192289352417 0.5184210538864136 0.8705621361732483 0.5190789699554443 0.8705621361732483 0.5249999761581421 0.8709319233894348 0.5256578922271729 0.8709319233894348 0.5289473533630371 0.8713017702102661 0.5296052694320679 0.8713017702102661 0.5309210419654846 0.8724112510681152 0.5328947305679321 0.8727810382843018 0.5328947305679321 0.8731508851051331 0.5335526466369629 0.8735207319259644 0.5335526466369629 0.8738905191421509 0.5328947305679321 0.8742603659629822 0.5328947305679321 0.8746301531791687 0.5322368144989014 0.875 0.5322368144989014 0.8753698468208313 0.5315789580345154 0.8753698468208313 0.5309210419654846 0.8757396340370178 0.5302631855010986 0.8757396340370178 0.5282894968986511 0.8761094808578491 0.5276315808296204 0.8761094808578491 0.512499988079071 0.8757396340370178 0.5118421316146851 0.8757396340370178 0.5019736886024475 0.8761094808578491 0.5013157725334167 0.8761094808578491 0.4973684251308441 0.8764792680740356 0.49671053886413574 0.8764792680740356 0.49407893419265747 0.8761094808578491 0.4934210479259491 0.8761094808578491 0.46578946709632874 0.8757396340370178 0.46513158082962036 0.8757396340370178 0.45197367668151855 0.8761094808578491 0.4513157904148102 0.8761094808578491 0.44736841320991516 0.8764792680740356 0.4467105269432068 0.8764792680740356 0.4440789520740509 0.8779585957527161 0.441447377204895 0.8761094808578491 0.441447377204895 0.8757396340370178 0.44078946113586426

P.S. Yes, you are possibly in the right. The initial idea to include the image extension could have been successful.

**Comment by laclouis5** [comment]
This does not look like a bounding box annotation file but rather a polygon annotation for segmentation judging by the format and the link you sent. Unfortunately, Globox is a package for **bounding boxes** only and does not support such annotation file. Polygon or segmentation annotations won't be supported, I want to keep Globox as simple and focused as possible.

For other tasks I suggest that you find another tool. Maybe Roboflow and their tool [Supervision](https://github.com/roboflow/supervision) can help you.
