### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by micdist** [laclouis5/globox#4]
Hi I'm trying to use your tool but something is getting in the way with imports.

here's the python code:
---------------------------------------------------------------------------------------
```
from ObjectDetectionEval import *
from pathlib import Path

def main() -> None:
    path = Path('D:/tesi/dataset/detr_imbalanced')  
    names_file = Path('D:/tesi/classi.txt')
    save_file = Path('yoloToCoco.json')

    annotations = AnnotationSet.from_yolo(path).map_labels(names_file)


    annotations.save_coco(save_file)


if __name__ == '__main__':
    main()
```
---------------------------------------------------------------------------------------

this is the error:
Traceback (most recent call last):
  File "D:\tesi\dataset\script\yoloToCoco.py", line 20, in <module>
    main()
  File "D:\tesi\dataset\script\yoloToCoco.py", line 10, in main
    annotations = AnnotationSet.from_yolo(path).map_labels(names_file)
NameError: name 'AnnotationSet' is not defined. Did you mean: 'annotations'?

Process finished with exit code 1

Any ideas? Thanks a lot

**Comment by laclouis5** [comment]
Can you try to pull the last commit and do use `from objtools import *` instead?

If that does not work could you try `from objtools import AnnotationSet`?

**Comment by micdist** [comment]
I cloned the whole thing again, the import changed: now it is seen as useful import but got this error:

  File "D:\tesi\dataset\script\yoloToCoco.py", line 10, in <module>
    annotations = AnnotationSet.from_yolo(path).map_labels(names_file)
  File "D:\tesi\coco-annotator\laclouis5\ObjectDetectionEval\objtools\annotationset.py", line 183, in from_yolo
    return AnnotationSet.from_txt(folder, 
  File "D:\tesi\coco-annotator\lalouis5\ObjectDetectionEval\objtools\annotationset.py", line 153, in from_txt
    assert image_folder is not None, "`image_folder` must be provided when `relative` is True to read image sizes"
AssertionError: `image_folder` must be provided when `relative` is True to read image sizes

Process finished with exit code 1

**Comment by laclouis5** [comment]
This error occurs because tout you are trying to load YOLO annotation files which are stored with relative coordinates (numbers in the interval 0...1) and this library required integral coordinates (in pixels), thus you should specify the image sizes. 

The simplest way to do that is to specify the image folder (where the images corresponding to the annotations you are trying to parse are stored) via the `image_folder` argument.

**Comment by micdist** [comment]
Great insight thanks :)
now I am trying "annotations = AnnotationSet.from_yolo(folder=path,
image_folder=path).map_labels(names_file)" but get error:

" File "D:\tesi\dataset\script\yoloToCoco.py", line 16, in <module>
    annotations.save_coco(save_file)
  File
"D:\tesi\coco-annotator\lalouis5\ObjectDetectionEval\objtools\annotationset.py",
line 448, in save_coco
    content = self.to_coco(label_to_id=label_to_id,
imageid_to_id=imageid_to_id, auto_ids=auto_ids)
  File
"D:\tesi\coco-annotator\lalouis5\ObjectDetectionEval\objtools\annotationset.py",
line 402, in to_coco
    assert native_ids or auto_ids, "For COCO, mappings from labels and
image ids to integer ids are required. They can be provided either by
argument or automatically by the `AnnotationSet` instance if it was created
with `AnnotationSet.from_coco()` or `AnnotationSet.from_coco_results()`.
You can also set `auto_ids` to True to automatically create image and label
ids (warning: this could cause unexpected compatibility issues with other
COCO datasets)."
AssertionError: For COCO, mappings from labels and image ids to integer ids
are required. They can be provided either by argument or automatically by
the `AnnotationSet` instance if it was created with
`AnnotationSet.from_coco()` or `AnnotationSet.from_coco_results()`. You can
also set `auto_ids` to True to automatically create image and label ids
(warning: this could cause unexpected compatibility issues with other COCO
datasets)."

my data is structured as: path-- folder of object 1
                                                   ....
                                                  -- folder of object n

Am I passing the arguments correctly?

Il giorno sab 20 ago 2022 alle ore 12:32 Lac Louis ***@***.***>
ha scritto:

**Comment by laclouis5** [comment]
Read the error message, it says that you can set `auto_ids` to `True` to solve the issue and this should work for you I guess.

**Comment by micdist** [comment]
Error gone, though I get:
Parsing: 0it [00:00, ?it/s]
Saving: 0it [00:00, ?it/s]

And an empty file: {"images": [], "annotations": [], "categories": []}

maybe all the imaeges should be in the same folder?


Il giorno sab 20 ago 2022 alle ore 17:19 Lac Louis ***@***.***>
ha scritto:

**Comment by laclouis5** [comment]
This simply means that the input folder is empty, i.e. the path `D:/tesi/dataset/detr_imbalanced` you are trying to parse in YOLO format does not contain any `.txt` file.

If for some reason your YOLO annotations don't have the `.txt` file extension, then you can use`AnnotationSet.from_txt(..., box_format=BoxFormat.XYWH, relative=True, file_extension=<YOUR_FILE_EXTENSION>)`.

For parsing YOLO annotations, you must specify the image folder. Just pass the same folder as for the annotations if images are stored in the same folder.

I'm not sure your copy of the repo is up to date, could you also update it? The package is now available on PyPI so you can just do `pip install globox` to install it. Just change to the import line to `from globox import *` and you should be good to go!
