### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by rlrahulkanojia** [laclouis5/globox#5]
Getting following error after installing.

Steps to reproduce:

>> python3 
>> from globox import ObjectDetectionEval

**Comment by laclouis5** [comment]
`ObjectDetectionEval` is the old package name, you can either import everything from `globox` with the wildcard:

```python
from globox import *
```

Or selectively import classes and functions:

```python
from globox import AnnotationSet
```
